spring:
  datasource:
    url: jdbc:h2:mem:mididb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /api/h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

upload:
  dir: /home/aryan/Desktop/visualizer/uploads